version: '3.7'
services:
    postgres:
        image: postgres:9.6
        container_name: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: airflow:latest
        container_name: airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        env_file:
            - .environment
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    
#     tor_server:
#         container_name: tor
#         image: dperson/torproxy
#         restart: always
#         environment:
#             - TOR_NewCircuitPeriod=2
#             - TOR_MaxCircuitDirtiness=1
#         ports:
#             - "8118:8118"
#             - "9050:9050"
#         networks:
#             tor_net:
#                 ipv4_address: 172.34.0.2

# networks:
#     tor_net:
#         driver: bridge
#         ipam:
#            config:
#              - subnet: 172.34.0.0/16
